blank_issues_enabled: false
contact_links:
  - name: ğŸ Bug in the Telebirr SDK
    url: https://github.com/glitch-telebirr/telebirr/issues/new/choose
    about: Do you think you have found a bug in the Telebirr JS SDK?
  - name: ğŸ”¥ Firebase Support
    url: https://firebase.google.com/support/
    about: If you have an urgent issue with your app, please contact support.
